In [27]:
import os
import json
import cv2

json_path="C:/Users/User/Desktop/Bbox_1901/label.json"
with open(json_path,"r")as f:
    coco_data=json.load(f)
print(coco_data)

{'images': [{'id': 0, 'file_name': 'ZED3_KSC_047355_L_P009301.png', 'width': 1920, 'height': 1080}, {'id': 1, 'file_name': 'ZED3_KSC_047356_L_P009302.png', 'width': 1920, 'height': 1080}, {'id': 2, 'file_name': 'ZED3_KSC_047357_L_P009303.png', 'width': 1920, 'height': 1080}, {'id': 3, 'file_name': 'ZED3_KSC_047358_L_P009304.png', 'width': 1920, 'height': 1080}, {'id': 4, 'file_name': 'ZED3_KSC_047359_L_P009305.png', 'width': 1920, 'height': 1080}, {'id': 5, 'file_name': 'ZED3_KSC_047361_L_P009306.png', 'width': 1920, 'height': 1080}, {'id': 6, 'file_name': 'ZED3_KSC_047362_L_P009307.png', 'width': 1920, 'height': 1080}, {'id': 7, 'file_name': 'ZED3_KSC_047363_L_P009308.png', 'width': 1920, 'height': 1080}, {'id': 8, 'file_name': 'ZED3_KSC_047364_L_P009309.png', 'width': 1920, 'height': 1080}, {'id': 9, 'file_name': 'ZED3_KSC_047365_L_P009310.png', 'width': 1920, 'height': 1080}, {'id': 10, 'file_name': 'ZED3_KSC_047366_L_P009311.png', 'width': 1920, 'height': 1080}, {'id': 11, 'file_na

In [35]:
#잘됐나 검증용
for image_info in coco_data["images"]:
    image_id = image_info["id"]
    image_name = image_info["file_name"]
    image_path = f"C:/Users/User/Desktop/Bbox_1901/{image_name}"
    image = cv2.imread(image_path)
    print(image)
    for annotation in coco_data["annotations"]:
        if annotation["image_id"] == image_id:
            bbox = annotation["bbox"]
            x, y, w, h = bbox
            x1, y1, x2, y2 = int(x), int(y), int(x + w), int(y + h)
            cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

    # 이미지 보여주기
    cv2.imshow(image_name, image)

cv2.waitKey(0)
cv2.destroyAllWindows()


[[[252 216 126]
  [251 215 125]
  [251 215 125]
  ...
  [ 79  74  63]
  [ 99  94  84]
  [ 98  93  83]]

 [[252 216 126]
  [251 215 125]
  [251 215 125]
  ...
  [ 71  66  58]
  [ 80  75  66]
  [ 86  82  74]]

 [[251 215 125]
  [251 215 125]
  [251 215 125]
  ...
  [ 60  54  48]
  [ 73  68  61]
  [ 83  78  71]]

 ...

 [[124 129 140]
  [135 140 151]
  [137 142 153]
  ...
  [ 63  79  85]
  [ 68  86  93]
  [ 69  90  98]]

 [[126 131 142]
  [127 132 143]
  [126 131 142]
  ...
  [ 58  72  74]
  [ 57  74  77]
  [ 56  74  79]]

 [[123 127 139]
  [126 132 143]
  [128 134 145]
  ...
  [ 55  61  64]
  [ 55  63  66]
  [ 52  62  65]]]
[[[251 200 121]
  [251 201 120]
  [250 200 119]
  ...
  [ 33  38  37]
  [ 47  54  48]
  [ 76  84  77]]

 [[251 200 120]
  [251 200 120]
  [251 200 121]
  ...
  [ 54  61  58]
  [ 67  74  67]
  [ 87  93  85]]

 [[251 200 121]
  [251 200 121]
  [251 200 121]
  ...
  [ 34  39  34]
  [ 29  32  27]
  [ 25  27  23]]

 ...

 [[138 143 154]
  [134 140 150]
  [133 138 149]
  ..

In [28]:
import albumentations as A
transform = A.Compose([
    A.Resize(width=960, height=540),  # 리사이즈 크기 지정
], bbox_params=A.BboxParams(format='coco', label_fields=['category_id']))


In [29]:
import numpy as np
images = coco_data['images']
annotations = coco_data['annotations']
print(images)
print(annotations)

[{'id': 0, 'file_name': 'ZED3_KSC_047355_L_P009301.png', 'width': 1920, 'height': 1080}, {'id': 1, 'file_name': 'ZED3_KSC_047356_L_P009302.png', 'width': 1920, 'height': 1080}, {'id': 2, 'file_name': 'ZED3_KSC_047357_L_P009303.png', 'width': 1920, 'height': 1080}, {'id': 3, 'file_name': 'ZED3_KSC_047358_L_P009304.png', 'width': 1920, 'height': 1080}, {'id': 4, 'file_name': 'ZED3_KSC_047359_L_P009305.png', 'width': 1920, 'height': 1080}, {'id': 5, 'file_name': 'ZED3_KSC_047361_L_P009306.png', 'width': 1920, 'height': 1080}, {'id': 6, 'file_name': 'ZED3_KSC_047362_L_P009307.png', 'width': 1920, 'height': 1080}, {'id': 7, 'file_name': 'ZED3_KSC_047363_L_P009308.png', 'width': 1920, 'height': 1080}, {'id': 8, 'file_name': 'ZED3_KSC_047364_L_P009309.png', 'width': 1920, 'height': 1080}, {'id': 9, 'file_name': 'ZED3_KSC_047365_L_P009310.png', 'width': 1920, 'height': 1080}, {'id': 10, 'file_name': 'ZED3_KSC_047366_L_P009311.png', 'width': 1920, 'height': 1080}, {'id': 11, 'file_name': 'ZED3_

In [30]:
test_path=""
image_folder="C:/Users/User/Desktop/Bbox_1901/"

In [31]:
# 이미지를 하나씩 처리하여 리사이즈
for img_info in images:
    img_id = img_info['id']
    img_path = os.path.join(image_folder, img_info['file_name'])
    # 이미지 로드
    img = cv2.imread(img_path)
    # 이미지를 numpy 배열로 변환
    img = np.array(img)
    
    # bounding box 정보 가져오기
    img_annotations = [ann for ann in annotations if ann['image_id'] == img_id]
    bboxes = [ann['bbox'] for ann in img_annotations]
    category_ids = [ann['category_id'] for ann in img_annotations]
    
    # 이미지 및 bounding box 리사이즈
    transformed = transform(image=img, bboxes=bboxes, category_id=category_ids)
    resized_img = transformed['image']
    resized_bboxes = transformed['bboxes']
    resized_category_ids = transformed['category_id']

    cv2.imwrite(img_path, resized_img)
    
    
    ############################################
    img_info['width'] = resized_img.shape[1]
    img_info['height'] = resized_img.shape[0]
    
    print(image_info['width'])

    # bounding box 정보 업데이트
    for ann, bbox in zip(img_annotations, resized_bboxes):
        ann['bbox'] = list(bbox)

# # JSON 파일 저장


1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920
1920


TypeError: unhashable type: 'dict'

In [34]:
j="C:/Users/User/Desktop/Bbox_1901/label.json"

with open(j, "w") as f:
    json.dump(json_path, f)